# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a448e97e3e9c4e017af698bc0998bd444b1918b31acffd82e23f5e3e8c0922eca28aa4c9697c0343b0d330af97e922ef3f3b0ec5da952286885d0531b80da796

test:
  secret_key_base: 8083eaf9e9710626d95df75871e83ab6e58bb182442335d2b06dd9acc71c767e94d1bbd3adf3ff76ad7fb7ee4a494e3cd074a651675b64da44a294d4ac1d3f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
